# frontend/app.yaml

# Specify a valid runtime, even though we only serve static files.
# This satisfies the App Engine requirement.
runtime: python312 # Or choose another valid runtime like nodejs20, etc.

service: default # Deploy as the default service

handlers:
  # Serve the CSS file
  - url: /style\.css
    static_files: style.css # Path relative to this app.yaml file
    upload: style\.css      # Regex matching the file to upload

  # Serve the JavaScript file
  - url: /script\.js
    static_files: script.js
    upload: script\.js

  # Serve the main index.html for the root path and any other unmatched paths
  - url: /.*
    static_files: index.html
    upload: index\.html

# Optional: Redirect all traffic to HTTPS (Good practice)
# secure: always

# Optional: Set expiration for static assets
# default_expiration: "1d"

# Optional: Specify scaling if needed, otherwise defaults apply
# automatic_scaling:
#  min_instances: 0
#  max_instances: 1 # Often 1 is sufficient for purely static frontend