runtime: python312
service: backend
# --- UPDATED ENTRYPOINT ---
entrypoint: gunicorn -b :$PORT -w 2 --threads 4 -k gthread app:app --timeout 120 --log-level info # Changed worker to gthread

instance_class: F4_1G # Keep F4 for memory

env_variables:
  GOOGLE_CLOUD_PROJECT: "autoquery-454320"
  TABLES_BUCKET: "autoquery-csv-data"
  TABLES_FOLDER: "tables_V2.0"
  # GCP_REGION: "us-central1" # Optional

automatic_scaling:
  target_cpu_utilization: 0.75
  min_instances: 0
  max_instances: 3
  # target_memory_utilization: 0.75

handlers:
- url: /.*
  script: auto
  secure: always