runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  # For example, if you need to set TABLES_DIR or other variables:
  TABLES_DIR: "C:/Users/kdelv/Documents/tables_V2.0"

# Optional: Adjust scaling if needed
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
