runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  # For example, if you need to set TABLES_DIR or other variables:
  TABLES_DIR: "./tables_V2.0"
  GOOGLE_APPLICATION_CREDENTIALS: "autoquery-450504-07c8eb3d217b.json"
  GOOGLE_CLOUD_PROJECT: "autoquery-450504"

# Optional: Adjust scaling if needed
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
